### ISSUE TITLE
I was crash when i run 

### ISSUE THREAD

**Issue by Rikuyal** [Thereallo1026/Jello-Client#5]
crash

**Comment by Thereallo1026** [comment]
That's some issue within skill fellow ganyu simp

**Comment by lonelil** [comment]
what

**Comment by MatrixAura** [comment]
Troubleshooting any problem without the error log is like driving with your eyes closed.

**Comment by lonelil** [comment]
Why tf did you reply 54 days later bruh 💀💀

**Comment by lonelil** [comment]
@Thereallo1026 just close this issue
